config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations"}
  resources :products do
    resources :comments
  end
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/landing_page'

  post 'simple_pages/thank_you'

  post 'payments/create'

  root 'simple_pages#index'

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HipsterFoods</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>


  </head>

  <body data-target=".navbar" id="topofpage">

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Home", root_path, class: "navbar-brand" %>
          <%= link_to "Featured", simple_pages_landing_page_path, class: "navbar-brand" %>
        </div> <!-- /navbar-header -->

        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right nav-tabs">
            <li class="link-logout">
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path) %>
            <% end %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right nav-tabs" role="tablist">
            <li class="link-first"><%= link_to "Products", products_path %></li>
            <li><%= link_to "Orders", orders_path %></li>
            <li><%= link_to "About", simple_pages_about_path %></li>
            <li class="link-last"><%= link_to "Contact", simple_pages_contact_path %></li>
          </ul>
          <div class="col-sm-3 col-md-3 navbar-right">
            <%= form_with(url: products_path, method: 'get', local: true, class: "navbar-form", role: "search") do |form| %>
              <div class="input-group">
                <%= form.label :q, 'Search for:', class: "sr-only" %>
                <%= form.text_field :q, id: 'q', value: params[:q], class: "form-control" %>
                <div class="input-group-btn">
                  <%= form.submit 'Search', class: "btn btn-default" %>
                  <!-- <i class="glyphicon glyphicon-search"></i> -->
                </div>
              </div>
            <% end %>
          </div>
        </div> <!-- /navbar-collapse-->
      </div> <!-- /nav -->
    </nav>

    <% if notice %>
      <p class="alert alert-info" role="alert"><%= notice %></p>
    <% elsif alert %>
      <p class="alert alert-warning" role="alert"><%= alert %></p>
    <% end %>

    <div class="content"><%= yield %></div>

    <footer class="footer">
      <div class="container-fluid">
        <div class="footer__element">&copy; Andreas Spannagel 2017</div>
      </div><!-- /container -->
    </footer>

  </body>
</html>